name: check-format

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm  
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install


      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Run prettier
        run: pnpm run format