name: check-format

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:

      - uses: pnpm/action-setup@v4
        name: Install pnpm  
        with:
           version: 9
           run_install: false

      - name: install prettier extension
        run: pnpm install prettier-plugin-tailwindcss

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
            dry: true
            prettier_options: --check